In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split

In [21]:
df = pd.read_csv("spamhamdata.csv", encoding="ISO-8859-1", sep="\t", header=None, names=["type", "text"])
df.head()

   type                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   type    5572 non-null   object
 1   text    5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [23]:
df.columns

Index(['type', 'text'], dtype='object')

In [24]:
import re
stop_words = []
with open("stop.txt") as f:
    stop_words = f.read()

stop_words = stop_words.split("\n")

In [25]:
def clean_text(i):
    i = re.sub("[^A-Za-z" "]+", " ", i).lower()
    i =  re.sub("[0-9" "]+", " ",i)
    w = []
    for word in i.split(" "):
        if len(word)>3:
            w.append(word)
        return (" ".join(w))

In [26]:
df.text = df.text.apply(clean_text)
df

      type  text
0      ham
1      ham
2     spam  free
3      ham
4      ham
...    ...   ...
5567  spam  this
5568   ham  will
5569   ham  pity
5570   ham
5571   ham  rofl

[5572 rows x 2 columns]

In [30]:
df = df.loc[df.text != " ",:]

In [32]:
def split_words(i):
    return [word for word in i.split(" ")]

In [34]:
X_train, X_test = train_test_split(df, test_size=0.2)

In [35]:
mail_count = CountVectorizer(analyzer=split_words).fit(df.text)

In [36]:
mail_matrix = mail_count.transform(df.text)

In [37]:
mail_matrix.shape

(5572, 709)

In [38]:
train_mail_matrix = mail_count.transform(X_train.text)

In [39]:
train_mail_matrix.shape

(4457, 709)

In [40]:
test_mail_matrix = mail_count.transform(X_test.text)

In [41]:
test_mail_matrix.shape

(1115, 709)

In [44]:
from sklearn.naive_bayes import MultinomialNB as MB

model_1 = MB()
model_1.fit(train_mail_matrix, X_train.type)

train_pred = model_1.predict(train_mail_matrix)
train_acc = np.mean(train_pred==X_train.type)
print("Train Accuracy:", train_acc)

test_pred = model_1.predict(test_mail_matrix)
test_acc = np.mean(test_pred==X_test.type)
print("Test Accuracy:", test_acc)

Train Accuracy: 0.923939869867624
Test Accuracy: 0.9040358744394619

In [47]:
from sklearn.naive_bayes import GaussianNB as GB

model_2 = GB()

#convert matrix to dense
train_dense = train_mail_matrix.toarray()
test_dense = test_mail_matrix.toarray()

model_2.fit(train_dense, X_train.type)

train_pred = model_2.predict(train_dense)
train_acc = np.mean(train_pred==X_train.type)
print("Train Accuracy:", train_acc)

test_pred = model_2.predict(test_dense)
test_acc = np.mean(test_pred==X_test.type)
print("Test Accuracy:", test_acc)

Train Accuracy: 0.39398698676239624
Test Accuracy: 0.35336322869955156

In [54]:
from sklearn.linear_model import LogisticRegression as LR
import numpy as np

model_3 = LR()
model_3.fit(train_mail_matrix, X_train.type)

train_pred = model_3.predict(train_mail_matrix)
train_acc = np.mean(train_pred == X_train.type)
print("Train Accuracy:", train_acc)

test_pred = model_3.predict(test_mail_matrix)
test_acc = np.mean(test_pred == X_test.type)
print("Test Accuracy:", test_acc)

Train Accuracy: 0.897689028494503
Test Accuracy: 0.8860986547085202